// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krirjygnsufvlipqhltt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyaXJqeWduc3VmdmxpcHFobHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDg3NDcsImV4cCI6MjA2ODk4NDc0N30.SzxyEVZYu7BFy6T-fKKyPI6WJblEMQj0W5HVnHa-2Sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});